steps:
  - id: 'Docker build'
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/lomatko/matka-frontend/frontend:latest', './collabothon2023']
  - id: 'Docker push'
    name: gcr.io/cloud-builders/docker
    args: ['push', 'europe-west1-docker.pkg.dev/lomatko/matka-frontend/frontend:latest']
images: ['europe-west1-docker.pkg.dev/lomatko/matka-backend/backend:latest']
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/lomatko/locations/europe-central2/workerPools/lomatko
